# .github/workflows/main.yml
name: Main
on:
  push:
    branches:
      - 'master'
      - 'main'
      - '!test'
      
jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
            zip -r archive.zip *
            ls

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: archive.zip
          folderId: 1dxpWM5UIsgjfrH2_Dsrr3dS9owzOGWzN
          credentials: ${{ secrets.credentials }}
          encoded: true
          overwrite: true
